---
title: "Group Practice"
author: "Aaron"
date: "June 18, 2016"
output: 
  html_document: 
    highlight: haddock
    theme: cosmo
---

### problem 1. Raspberries & Strawberries

```{r message=F}

library(lpSolveAPI)
library(dplyr)

```

Make linear optimization. 

```{r}

lpmodel <- make.lp(0, 2)
lp.control(lpmodel, sense="max")

set.objfn(lpmodel, c(1.5,2.1))

add.constraint(lpmodel, c(1,1), "<=", 200)
add.constraint(lpmodel, c(2.5, 4), "<=", (800-3.8-4))
```

```{r}

solve(lpmodel) # model can be solved

get.objective(lpmodel)
get.variables(lpmodel)

```

We should produced `5.2` strawberreies and `194.8` raspberries 

##### Farmers 

```{r}

lpmodel <- make.lp(0, 4)
lp.control(lpmodel, sense="max")

set.objfn(lpmodel, c(1.3*110,2*30,3.5*90,2.75*80))

add.constraint(lpmodel, c(1,1,1,1), "<=", 175)
add.constraint(lpmodel, c(110, 30, 90, 80), "<=", 8000)
add.constraint(lpmodel, c(120, 210, 130, 190), "<=", 35000)

```


```{r}

solve(lpmodel) # model can be solved

get.objective(lpmodel)
get.variables(lpmodel)

```

We should all invest in `88.88889` corn

#### Simulation 

```{r}

library(simmer)

create_trajectory("sandwich shop") %>% 
    seize("sandwich_maker", 1) %>% 
    timeout(function() rnorm(1, 5)) %>% 
    release("sandwich_maker", 1) -> t0

```

```{r}

simmer("Sandwich Joe") %>% 
    add_resource("sandwich_maker", 1) %>% 
    add_resource("sandwich_maker_2", 3) %>% 
    add_generator("customer", t0, function() rnorm(1, 10, 1)) -> env

env %>% run(until=120)

```

```{r}

plot_evolution_arrival_times(env, type = "waiting_time")

```


```{r}

env %>% run(until=200)

```

```{r}

plot_evolution_arrival_times(env, type = "waiting_time")

```















